- name: nginx installation
  hosts: all
  become: true
  tasks:
    - name: install nginx on ubuntu
      apt:
        name: nginx
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install nginx on amazon linux
      yum:
        name: nginx
        state: latest
      when: ansible_distribution == "Amazon"

    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: true
